sudo: required
language: python
python:
  - "3.5"
os:
  - linux
  # - osx
install: true
before_script:
  - sudo apt update
  - sudo apt upgrade
  - sudo apt install build-essential lazarus subversion
  - sudo ln -sfv /usr/lib/x86_64-linux-gnu/libstdc++.so.6 /usr/lib/x86_64-linux-gnu/libstdc++.so
  - sudo ln -sfv /lib/x86_64-linux-gnu/libgcc_s.so.1 /lib/x86_64-linux-gnu/libgcc_s.so
script:
  - make all
notifications:
  email: false
